### ISSUE TITLE
Module_path nodes are missing

### ISSUE THREAD

**Issue by undu** [tree-sitter/tree-sitter-ocaml#40]
Currentlty this expression:
```ocaml
  let foo = Int.zero in
```
is parsed as
```
value_definition [2, 1] - [20, 1])
  let_binding [6, 1] - [20, 1])
    value_name [6, 1] - [9, 1])
    value_path [12, 1] - [20, 1])
      module_name [12, 1] - [15, 1])
      value_path [16, 1] - [20, 1])
        value_name [16, 1] - [20, 1])
```

This makes it difficult to capture the value_name as exception or function if it's the case. It hinders [highlighting](https://github.com/tree-sitter/tree-sitter-ocaml/pull/39) because the pattern is forced to match deeply-nested structures.

Reading the specs the structure should be different:
```scheme
(value_definition
  (let_binding
    (value_name)
    (value_path
      (module_path (module_name))
      (value_name)
    )
  )
)
```
I suspect this is bound to affect a few nodes as per the [specs](https://caml.inria.fr/pub/docs/manual-ocaml/names.html):
```
value-path ::= [ module-path . ]  value-name
constr ::= [ module-path . ]  constr-name
typeconstr ::= [ extended-module-path . ]  typeconstr-name
field ::= [ module-path . ]  field-name
modtype-path ::= [ extended-module-path . ]  modtype-name
class-path ::= [ module-path . ]  class-name
classtype-path ::= [ extended-module-path . ]  class-name
module-path ::= module-name  { . module-name } 
extended-module-path ::= extended-module-name  { . extended-module-name }
extended-module-name ::= module-name  { ( extended-module-path ) }
```

**Comment by 314eter** [comment]
The specs you're referring to are just the manual and are rather informal (and sometimes incomplete). The only real reference is the [implementation](https://github.com/ocaml/ocaml/blob/trunk/parsing/parser.mly).

I know that the value paths are messy, but they are difficult to change without generating a lot of conflicts. I wrote this before highlighting was possible, so that wasn't a problem then. Maybe it's possible to simplify the grammar, but it won't be easy.

One problem is that the tree-sitter parser can be used both for .ml and .mli files. This causes a conflict in `include_statement`, and all other conflicts are a consequence of this one.

**Comment by undu** [comment]
Thanks for the explanation, it's my first trip into the ocaml ast.

> One problem is that the tree-sitter parser can be used both for .ml and .mli files. This causes a conflict in include_statement, and all other conflicts are a consequence of this one.

That's unfortunate, is there something preventing having a parser for each of them?

**Comment by 314eter** [comment]
It's tree-sitter convention to have only one parser for each language. There is for example only one python parser, not separate ones for python2 and python3. So in theory it's possible to have separate parsers (although they will be exactly the same, only with different entry points), but I'm not sure that's the right solution.

**Comment by maxbrunsfeld** [comment]
Note that, if it's always possible to tell `.ml` from `.mli` (using the file extension), then it would be reasonable to have separate parsers. We do something similar, for example, in [tree-sitter-typescript](https://github.com/tree-sitter/tree-sitter-typescript), because `.ts` and `.tsx` files have slightly different but incompatible syntax.

**Comment by 314eter** [comment]
That's good to know, that will make some simplifications possible, and hopefully reduce the grammar size. I'll try that out later.

**Comment by 314eter** [comment]
This is fixed in #41.

@undu Can you try this out? Did you notice other problems with the syntax tree that make highlighting difficult?

**Comment by undu** [comment]
Thanks so much! I'll try to use it tomorrow for ocaml files. I'm first need to change filetype detection in vim because mli and ml files have been detected as the same kind of files until now.

This was the only issue I found when trying to highlight.

**Comment by 314eter** [comment]
I'm not sure the current grammar names (`ocaml` and `mli`) are a good choice. Maybe `ocamli` or `ocaml_interface` for mli files is better?

**Comment by undu** [comment]
Personally I like `ocamli`, but I don't think that's a standard name. I'll ask around.

**Comment by maxbrunsfeld** [comment]
I'd be in favor of `ocaml_interface` or `ocaml_header`. Both terms 'header' and 'interface' seem to be used in the documentation [here](https://ocaml.org/learn/tutorials/filenames.html).

**Comment by 314eter** [comment]
The scope in the Visual Studio Code [extension](https://github.com/ocamllabs/vscode-ocaml-platform/blob/master/syntaxes/ocaml.interface.json) is `source.ocaml.interface`. The term 'header' in the tutorial is probably meant for people familiar with C header files, I've never heard it in an OCaml context.

So `ocaml_interface` is probably the best choice.
