### ISSUE TITLE
Can't distinguish between "function, variable" and "variable"

### ISSUE THREAD

**Issue by rbjorklin** [tree-sitter/tree-sitter-ocaml#61]
I'm not sure this is the correct repo to report this, let me know if it isn't.

I'm trying to tweak a colorscheme and I'm having a hard time telling different elements apart. I'm using [nvim-treesitter-playground](https://github.com/nvim-treesitter/playground) to identify elements using `TSHighlightCapturesUnderCursor`.

I'm trying to have functions show up as blue and variables as white. The colorscheme seems to be applied to the last TS property applied to an element which causes a discrepancy between a elements that have the same properties but in a different order as can be seen in the below screenshots.

Could something be done to make this consistent? Does it make sense for an element to only have one property?

![Screenshot from 2022-10-23 18-40-05](https://user-images.githubusercontent.com/1704798/197431447-d96e0180-ffde-432d-8a9c-071ed75d29be.png)
![Screenshot from 2022-10-23 18-36-06](https://user-images.githubusercontent.com/1704798/197431448-c0b2b592-c2e9-424c-b4c9-987f61914689.png)
![Screenshot from 2022-10-23 18-35-28](https://user-images.githubusercontent.com/1704798/197431449-184dee25-e444-474b-a470-354ac7c51359.png)

**Comment by undu** [comment]
Those are highlight groups, which are assigned according to https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/ocaml/highlights.scm
About only ever wanting a single property being shown, I don't think it's possible to do so, especially in cases like the second one which it's a function 'variable' (or binding). If there is some mischaracterization it makes sense to fix it. (probably the third case)

The actual style when two properties are match depend on nvim decides to apply them. It could be that if the two properties have complementary styles that can be applies at the same time, (one color, one shape). Other than that I'd be reticent to change the properties because it might change other colorschemes as they may depend on this
